/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import static db.Basedcon.conectarbd;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JFrame;

/**
 *
 * @author Acer
 */
public class Principalview extends javax.swing.JFrame {
    /**
     * Creates new form Principalview
     */
    public JFrame getjframe(){
        return this;
    }
    public Principalview() {
        initComponents();
        Registro reg= new Registro();
        Ingreso ingr = new Ingreso();
        Registro1 reg1= new Registro1();
        Ingreso1 ingr1 = new Ingreso1();
        Registro2 reg2= new Registro2();
        Ingreso2 ingr2 = new Ingreso2();
        panelSlide1.init(reg,reg1,reg2,ingr,ingr1,ingr2);
        panelSlide1.setAnimate(5);
        conectarbd();
        setLocationRelativeTo(null);
        //panelSlide2.init(new Registro(),new Ingreso());
        //panelSlide2.setAnimate(5);
    }
    /*public static void cerrarventana(){
        this.setVisible(false);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regtut = new javax.swing.JButton();
        panelSlide1 = new vista.PanelSlide();
        regest = new javax.swing.JButton();
        regps = new javax.swing.JButton();
        ingest = new javax.swing.JButton();
        ingtut = new javax.swing.JButton();
        ingps = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        regtut.setText("Tutor");
        regtut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regtutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelSlide1Layout = new javax.swing.GroupLayout(panelSlide1);
        panelSlide1.setLayout(panelSlide1Layout);
        panelSlide1Layout.setHorizontalGroup(
            panelSlide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelSlide1Layout.setVerticalGroup(
            panelSlide1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );

        regest.setText("Estudiante");
        regest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regestActionPerformed(evt);
            }
        });

        regps.setText("Psicologo(a)");
        regps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regpsActionPerformed(evt);
            }
        });

        ingest.setText("Estudiante");
        ingest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingestActionPerformed(evt);
            }
        });

        ingtut.setText("Tutor");
        ingtut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingtutActionPerformed(evt);
            }
        });

        ingps.setText("Psicologo(a)");
        ingps.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ingpsActionPerformed(evt);
            }
        });

        jLabel1.setText("REGISTRO");

        jLabel2.setText("INGRESO");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ingest)
                    .addComponent(regest))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(regtut)
                    .addComponent(ingtut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ingps)
                    .addComponent(regps))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(159, 159, 159))))
            .addComponent(panelSlide1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(regtut)
                    .addComponent(regps)
                    .addComponent(regest))
                .addGap(4, 4, 4)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ingps)
                    .addComponent(ingtut)
                    .addComponent(ingest))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelSlide1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ingestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingestActionPerformed
        // TODO add your handling code here:
        panelSlide1.show(3);
    }//GEN-LAST:event_ingestActionPerformed

    private void regtutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regtutActionPerformed
        // TODO add your handling code here:
        panelSlide1.show(1);
    }//GEN-LAST:event_regtutActionPerformed

    private void ingpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingpsActionPerformed
        // TODO add your handling code here:
        panelSlide1.show(5);
    }//GEN-LAST:event_ingpsActionPerformed

    private void regestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regestActionPerformed
        // TODO add your handling code here:
        panelSlide1.show(0);
    }//GEN-LAST:event_regestActionPerformed

    private void ingtutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ingtutActionPerformed
        // TODO add your handling code here:
        panelSlide1.show(4);
    }//GEN-LAST:event_ingtutActionPerformed

    private void regpsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regpsActionPerformed
        // TODO add your handling code here:
        panelSlide1.show(2);
    }//GEN-LAST:event_regpsActionPerformed
    /*public static void setvis(boolean x){
        this.setVisible(x);
    }*/
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principalview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principalview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principalview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principalview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principalview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ingest;
    private javax.swing.JButton ingps;
    private javax.swing.JButton ingtut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private vista.PanelSlide panelSlide1;
    private javax.swing.JButton regest;
    private javax.swing.JButton regps;
    private javax.swing.JButton regtut;
    // End of variables declaration//GEN-END:variables
}
